### PR TITLE
CMEK Azure info

### PR DESCRIPTION
**Pull request by fiquick**

### CODE REVIEW

**Comment by fiquick** [comment]
[Additional ways to configure Azure Key Vault for CMK](https://trello.com/c/bumHsxX9/396-additional-ways-to-configure-azure-key-vault-for-cmk)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-559.surge.sh

Updated pages:
- [Encryption](https://neo4j-docs-aura-559.surge.sh/aura/classic/platform/security/encryption)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-559.surge.sh

Updated pages:
- [Encryption](https://neo4j-docs-aura-559.surge.sh/aura/classic/platform/security/encryption)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-559.surge.sh

Updated pages:
- [Encryption](https://neo4j-docs-aura-559.surge.sh/aura/classic/platform/security/encryption)

**Review by GuangxueCao — APPROVED** [review]
Looks great to me 🚀
Thanks @fiquick

**Review by GuangxueCao — APPROVED** [review]

**Comment by fiquick** [comment]
Thanks for reviewing @GuangxueCao

**Pull request merged**
