### PR TITLE
CMEK for Azure

### PR DESCRIPTION
**Pull request by fiquick**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-379.surge.sh

Updated pages:
- [Encryption](https://neo4j-docs-aura-379.surge.sh/aura/platform/security/encryption)

**Comment by fiquick** [comment]
[CMEK Azure](https://trello.com/c/apxD8ETY/321-cmek-azure)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-379.surge.sh

Updated pages:
- [Encryption](https://neo4j-docs-aura-379.surge.sh/aura/platform/security/encryption)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-379.surge.sh

Updated pages:
- [Encryption](https://neo4j-docs-aura-379.surge.sh/aura/platform/security/encryption)

**Pull request closed without merging**
