### PR TITLE
resize downwards

### PR DESCRIPTION
**Pull request by fiquick**

### CODE REVIEW

**Comment by fiquick** [comment]
[Document - Allow resize downwards based on current instance storage](https://trello.com/c/NM9gXU61/283-document-allow-resize-downwards-based-on-current-instance-storage)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-520.surge.sh

Updated pages:
- [Instance actions](https://neo4j-docs-aura-520.surge.sh/aura/auradb/managing-databases/database-actions)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-520.surge.sh

Updated pages:
- [Instance actions](https://neo4j-docs-aura-520.surge.sh/aura/auradb/managing-databases/database-actions)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-520.surge.sh

Updated pages:
- [Instance actions](https://neo4j-docs-aura-520.surge.sh/aura/auradb/managing-databases/database-actions)

**Pull request merged**
