### PR TITLE
AuraDB VDC architecture tutorial

### PR DESCRIPTION
**Pull request by fiquick**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-492.surge.sh

New pages:
- [AuraDB Virtual Dedicated Cloud architecture](https://neo4j-docs-aura-492.surge.sh/aura/tutorials/auradb-vdc-cloud-architecture)

**Comment by fiquick** [comment]
[Aura security - architecture diagram](https://trello.com/c/jq5pfg48/310-aura-security-architecture-diagram)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-492.surge.sh

New pages:
- [AuraDB Virtual Dedicated Cloud architecture](https://neo4j-docs-aura-492.surge.sh/aura/tutorials/auradb-vdc-cloud-architecture)

**Comment by fiquick** [comment]
Closing and putting into a word doc - intro to security

**Pull request closed without merging**
