### PR TITLE
Add Aura DS table

### PR DESCRIPTION
**Pull request by fiquick**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-540.surge.sh

Updated pages:
- [Backup, export and restore](https://neo4j-docs-aura-540.surge.sh/aura/auradb/managing-databases/backup-restore-export)
- [Backup, export, and restore](https://neo4j-docs-aura-540.surge.sh/aura/aurads/managing-instances/backup-restore-export)

**Review by AlexicaWright — APPROVED** [review]
👍

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-540.surge.sh

Updated pages:
- [Backup, export and restore](https://neo4j-docs-aura-540.surge.sh/aura/auradb/managing-databases/backup-restore-export)
- [Backup, export, and restore](https://neo4j-docs-aura-540.surge.sh/aura/aurads/managing-instances/backup-restore-export)

**Comment by fiquick** [comment]
[Add DS backup retention table](https://trello.com/c/WyYdXHqG/406-add-ds-backup-retention-table)

**Pull request merged**
