### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by nvitucci**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-311.surge.sh

Updated pages:
- [Projecting graphs and using the Graph Catalog](https://neo4j-docs-aura-311.surge.sh/aura/aurads/tutorials/graph-catalog)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-311.surge.sh

Updated pages:
- [Architecture](https://neo4j-docs-aura-311.surge.sh/aura/aurads/architecture)
- [Projecting graphs and using the Graph Catalog](https://neo4j-docs-aura-311.surge.sh/aura/aurads/tutorials/graph-catalog)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-311.surge.sh

Updated pages:
- [Architecture](https://neo4j-docs-aura-311.surge.sh/aura/aurads/architecture)
- [Loading and streaming back data with Apache Arrow](https://neo4j-docs-aura-311.surge.sh/aura/aurads/tutorials/arrow-examples)
- [Projecting graphs and using the Graph Catalog](https://neo4j-docs-aura-311.surge.sh/aura/aurads/tutorials/graph-catalog)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-311.surge.sh

Updated pages:
- [Architecture](https://neo4j-docs-aura-311.surge.sh/aura/aurads/architecture)
- [Loading and streaming back data with Apache Arrow](https://neo4j-docs-aura-311.surge.sh/aura/aurads/tutorials/arrow-examples)
- [Projecting graphs and using the Graph Catalog](https://neo4j-docs-aura-311.surge.sh/aura/aurads/tutorials/graph-catalog)

**Review by fiquick — APPROVED** [review]
Links look good to me

**Pull request merged**
