### PR TITLE
retention table feedback

### PR DESCRIPTION
**Pull request by fiquick**
Original table available at: https://neo4j.com/docs/aura/auradb/managing-databases/backup-restore-export/#_retention_periods

Suggested table in spreadsheet: https://docs.google.com/spreadsheets/d/1fg8LpfWtLVUEw5r30Xmt9aRkOhrMXa3iK81i33pd4zw/edit?gid=582644898#gid=582644898

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-529.surge.sh

Updated pages:
- [Backup, export and restore](https://neo4j-docs-aura-529.surge.sh/aura/auradb/managing-databases/backup-restore-export)

**Comment by fiquick** [comment]
[Backup retention - implement feedback](https://trello.com/c/qcKxZi7S/394-backup-retention-implement-feedback)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-529.surge.sh

Updated pages:
- [Backup, export and restore](https://neo4j-docs-aura-529.surge.sh/aura/auradb/managing-databases/backup-restore-export)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-529.surge.sh

Updated pages:
- [Backup, export and restore](https://neo4j-docs-aura-529.surge.sh/aura/auradb/managing-databases/backup-restore-export)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-529.surge.sh

Updated pages:
- [Backup, export and restore](https://neo4j-docs-aura-529.surge.sh/aura/auradb/managing-databases/backup-restore-export)

**Pull request closed without merging**
