### PR TITLE
Fix style: Sentences on new lines

### PR DESCRIPTION
**Pull request by nvitucci**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-419.surge.sh

Updated pages:
- [Connecting applications](https://neo4j-docs-aura-419.surge.sh/aura/auradb/connecting-applications/overview)
- [Connecting to an instance](https://neo4j-docs-aura-419.surge.sh/aura/auradb/getting-started/connect-database)
- [Creating an instance](https://neo4j-docs-aura-419.surge.sh/aura/auradb/getting-started/create-database)
- [Importing data](https://neo4j-docs-aura-419.surge.sh/aura/auradb/importing/importing-data)
- [Instance actions](https://neo4j-docs-aura-419.surge.sh/aura/auradb/managing-databases/database-actions)
- [Architecture](https://neo4j-docs-aura-419.surge.sh/aura/aurads/architecture)
- [Connecting with Neo4j applications](https://neo4j-docs-aura-419.surge.sh/aura/aurads/connecting/neo4j-applications)
- [Connecting with Python](https://neo4j-docs-aura-419.surge.sh/aura/aurads/connecting/python)
- [Creating an AuraDS instance](https://neo4j-docs-aura-419.surge.sh/aura/aurads/create-instance)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-419.surge.sh

Updated pages:
- [Connecting applications](https://neo4j-docs-aura-419.surge.sh/aura/auradb/connecting-applications/overview)
- [Connecting to an instance](https://neo4j-docs-aura-419.surge.sh/aura/auradb/getting-started/connect-database)
- [Creating an instance](https://neo4j-docs-aura-419.surge.sh/aura/auradb/getting-started/create-database)
- [Importing data](https://neo4j-docs-aura-419.surge.sh/aura/auradb/importing/importing-data)
- [Instance actions](https://neo4j-docs-aura-419.surge.sh/aura/auradb/managing-databases/database-actions)
- [Architecture](https://neo4j-docs-aura-419.surge.sh/aura/aurads/architecture)
- [Connecting with Neo4j applications](https://neo4j-docs-aura-419.surge.sh/aura/aurads/connecting/neo4j-applications)
- [Connecting with Python](https://neo4j-docs-aura-419.surge.sh/aura/aurads/connecting/python)
- [Creating an AuraDS instance](https://neo4j-docs-aura-419.surge.sh/aura/aurads/create-instance)

**Comment by fiquick** [comment]
[Fix style: Sentences on new lines](https://trello.com/c/uaNKRVCO/355-fix-style-sentences-on-new-lines)

**Review by fiquick — APPROVED** [review]

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-419.surge.sh

Updated pages:
- [Connecting applications](https://neo4j-docs-aura-419.surge.sh/aura/auradb/connecting-applications/overview)
- [Connecting to an instance](https://neo4j-docs-aura-419.surge.sh/aura/auradb/getting-started/connect-database)
- [Creating an instance](https://neo4j-docs-aura-419.surge.sh/aura/auradb/getting-started/create-database)
- [Importing data](https://neo4j-docs-aura-419.surge.sh/aura/auradb/importing/importing-data)
- [Instance actions](https://neo4j-docs-aura-419.surge.sh/aura/auradb/managing-databases/database-actions)
- [Architecture](https://neo4j-docs-aura-419.surge.sh/aura/aurads/architecture)
- [Connecting with Neo4j applications](https://neo4j-docs-aura-419.surge.sh/aura/aurads/connecting/neo4j-applications)
- [Connecting with Python](https://neo4j-docs-aura-419.surge.sh/aura/aurads/connecting/python)
- [Creating an AuraDS instance](https://neo4j-docs-aura-419.surge.sh/aura/aurads/create-instance)

**Pull request merged**
