### PR TITLE
More style fixes

### PR DESCRIPTION
**Pull request by nvitucci**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-454.surge.sh

Updated pages:
- [Creating an instance](https://neo4j-docs-aura-454.surge.sh/aura/auradb/getting-started/create-database)
- [Advanced metrics](https://neo4j-docs-aura-454.surge.sh/aura/auradb/managing-databases/advanced-metrics)
- [Advanced metrics](https://neo4j-docs-aura-454.surge.sh/aura/aurads/managing-instances/advanced-metrics)
- [Request and download logs](https://neo4j-docs-aura-454.surge.sh/aura/platform/logging/download-logs)
- [Encryption](https://neo4j-docs-aura-454.surge.sh/aura/platform/security/encryption)
- [User management](https://neo4j-docs-aura-454.surge.sh/aura/platform/user-management)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-454.surge.sh

Updated pages:
- [Creating an instance](https://neo4j-docs-aura-454.surge.sh/aura/auradb/getting-started/create-database)
- [Advanced metrics](https://neo4j-docs-aura-454.surge.sh/aura/auradb/managing-databases/advanced-metrics)
- [Advanced metrics](https://neo4j-docs-aura-454.surge.sh/aura/aurads/managing-instances/advanced-metrics)
- [Request and download logs](https://neo4j-docs-aura-454.surge.sh/aura/platform/logging/download-logs)
- [Encryption](https://neo4j-docs-aura-454.surge.sh/aura/platform/security/encryption)
- [User management](https://neo4j-docs-aura-454.surge.sh/aura/platform/user-management)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-454.surge.sh

Updated pages:
- [Creating an instance](https://neo4j-docs-aura-454.surge.sh/aura/auradb/getting-started/create-database)
- [Advanced metrics](https://neo4j-docs-aura-454.surge.sh/aura/auradb/managing-databases/advanced-metrics)
- [Instance actions](https://neo4j-docs-aura-454.surge.sh/aura/auradb/managing-databases/database-actions)
- [Loading CSV files](https://neo4j-docs-aura-454.surge.sh/aura/aurads/importing-data/load-csv)
- [Advanced metrics](https://neo4j-docs-aura-454.surge.sh/aura/aurads/managing-instances/advanced-metrics)
- [Authentication](https://neo4j-docs-aura-454.surge.sh/aura/platform/api/authentication)
- [Overview](https://neo4j-docs-aura-454.surge.sh/aura/platform/api/overview)
- [Request and download logs](https://neo4j-docs-aura-454.surge.sh/aura/platform/logging/download-logs)
- [Query log analyzer](https://neo4j-docs-aura-454.surge.sh/aura/platform/logging/query-log-analyzer)

**Review by fiquick — COMMENTED** [review]
looks good! it's a smart tool!

**Comment by nvitucci** [comment]
@fiquick Can you approve it if everything is good?

**Review by fiquick — APPROVED** [review]

**Pull request merged**
