### PR TITLE
sso screenshot

### PR DESCRIPTION
**Pull request by fiquick**

### CODE REVIEW

**Comment by fiquick** [comment]
[SSO - request to add screenshots (UPX only)](https://trello.com/c/u7PRjpAe/405-sso-request-to-add-screenshots-upx-only)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-546.surge.sh

Updated pages:
- [Single Sign-On (SSO)](https://neo4j-docs-aura-546.surge.sh/aura/platform/security/single-sign-on)

**Review by AlexicaWright — APPROVED** [review]
Do we want to display Okta as chosen IdP? Just a thought, if so, I say merge!

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-546.surge.sh

Updated pages:
- [Single Sign-On (SSO)](https://neo4j-docs-aura-546.surge.sh/aura/platform/security/single-sign-on)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-546.surge.sh

Updated pages:
- [Single Sign-On (SSO)](https://neo4j-docs-aura-546.surge.sh/aura/platform/security/single-sign-on)

**Pull request merged**
