### PR TITLE
add draft Azure marketplace documentation

### PR DESCRIPTION
**Pull request by fiquick**
Aman is trying to get an Azure account with subscription access from IT. The main instructions for trying it out are here: https://docs.google.com/document/d/1HXE7xK36Vb34I4dK3jr1rYSKHc3zdHR1_Kx_V9UHhIw/edit#heading=h.5kcstiaa0uek
Creating a draft PR for this, so we have something driving us to get it out.

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-352.surge.sh

Updated pages:
- [Aura with cloud provider marketplaces](https://neo4j-docs-aura-352.surge.sh/aura/platform/cloud-providers)

**Comment by fiquick** [comment]
[Create a draft PR for "Aura Professional via Cloud Provider Marketplaces"](https://trello.com/c/uaakZ9qv/320-create-a-draft-pr-for-aura-professional-via-cloud-provider-marketplaces)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-352.surge.sh

Updated pages:
- [Aura with cloud provider marketplaces](https://neo4j-docs-aura-352.surge.sh/aura/platform/cloud-providers)

**Comment by aman-neo** [comment]
@fiquick The last section should say Azure, not GCP https://take.ms/DorgK. Apart from that LGTM!

**Comment by aman-neo** [comment]
LGTM!

**Review by aman-neo — APPROVED** [review]
LGTM!

**Pull request merged**
