### PR TITLE
Add business critical labels to Aura advanced metrics and QLA docs

### PR DESCRIPTION
**Pull request by alexnb**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-453.surge.sh

Updated pages:
- [Advanced metrics](https://neo4j-docs-aura-453.surge.sh/aura/auradb/managing-databases/advanced-metrics)

**Comment by SeBBBe** [comment]
Add the label also for QLA? :)

**Review by AlexicaWright — APPROVED** [review]
LGTM 👍

**Review by SeBBBe — APPROVED** [review]

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-453.surge.sh

Updated pages:
- [Advanced metrics](https://neo4j-docs-aura-453.surge.sh/aura/auradb/managing-databases/advanced-metrics)
- [Query log analyzer](https://neo4j-docs-aura-453.surge.sh/aura/platform/logging/query-log-analyzer)

**Pull request merged**
